server:
  port: 6969

spring:
  api:
    security:
      token:
        secret: CHUT0M3T-RO

  application:
    name: chutometro
  output:
    ansi:
      enabled: always

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

